name: SystemLogs
author: BlusterySasha
main: System\Main\Main
version: 0.0.1
api: 3.0.0

commands:
  info:
    description: "Player/Server info"
    permission: system.info

permissions:
  system.info:
    default: op